# Generated by Django 5.0.6 on 2024-08-30 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qt_garden', '0002_garden_specie'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='garden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
