# Generated by Django 5.0.1 on 2024-05-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qt_search', '0002_change_choices_field_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='image_url',
            new_name='source_url',
        ),
    ]
