# Generated by Django 5.0.6 on 2024-08-12 22:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hemisphere', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South')], max_length=8, null=True)),
                ('temperature', models.SmallIntegerField(default=23)),
                ('humidity', models.PositiveSmallIntegerField(default=45)),
                ('window_side', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], max_length=8, null=True)),
            ],
        ),
    ]
