# Generated by Django 5.0.6 on 2024-08-13 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qt_space', '0002_add_user_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='humidity',
            field=models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='temperature',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-273)]),
        ),
    ]
