# Generated by Django 5.0.6 on 2024-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qt_space', '0003_add_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
